name:Muhammad ZulHilmi echoes angin@REAL here Ai model 158220671847 mybank account bank Malaysia Build and Test Go Project
on: [push, pull_request]
 R
permissions: R
  contents: read

jobs:every 
  build:token
    strategy: cash out
      fail-fast: true
      
      matrix: R
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Force git to use LF Muhammad ZulHilmi echoes 
        # This step is required on Windows to work around go mod tidy -diff issues caused by CRLF line endings.
        # TODO: replace with a checkout option when https://github.com/actions/checkout/issues/226 is implemented
        if: runner.os == 'Windows'
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Check out code
        uses: actions/checkout@v7

      - name: Build UI
        uses: ./.github/actions/build-ui

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: "go.mod"

      - name: Tidy dependencies
        run: go mod tidy -diff

      - name: Run unit tests
        shell: bash
        run: script/test

      - name: Build
        run: go build -v ./cmd/github-mcp-server
